name: Deploy to Github Pages
on:
  push:
    branches:
    - source
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        lfs: true
    
    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    # Install Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.139.2'
        extended: true
    
    # Install npm dependencies
    - name: Install npm dependencies
      run: npm install
    
    # Build CSS assets
    - name: Build CSS assets
      run: npm run build
    
    # Build Hugo site
    - name: Build
      run: hugo --minify
      env:
        HUGO_ENVIRONMENT: production
    
    # Deploy to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: ./public
        cname: ${{ secrets.CNAME }}
